{
 "title": "gin监控",
 "time": { "from": "2021-08-07T06:12:10.258Z", "to": "2021-08-07T06:14:54.024Z" },
 "panels": [
  {
   "title": "协程数量",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"ginadmin\"}"
    }
   ]
  },
  {
   "title": "GC次数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds_count{job=\"ginadmin\"}"
    }
   ]
  },
  {
   "title": "线程数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_threads{job=\"ginadmin\"}"
    }
   ]
  },
  {
   "title": "内存统计",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "堆空间分配",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"ginadmin\"}",
       "legendFormat": "服务分配的堆内存字节数"
      },
      {
       "expr": "go_memstats_heap_idle_bytes{job=\"ginadmin\"}",
       "legendFormat": "空闲的堆内存"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{job=\"ginadmin\"}",
       "legendFormat": "正在使用的堆内存字节数"
      },
      {
       "expr": "go_memstats_heap_released_bytes{job=\"ginadmin\"}",
       "legendFormat": "返回给OS的堆内存"
      },
      {
       "expr": "go_memstats_heap_sys_bytes{job=\"ginadmin\"}",
       "legendFormat": "系统分配的作为运行栈的内存"
      }
     ]
    },
    {
     "title": "系统内存占用",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_sys_bytes{job=\"ginadmin\"}",
       "legendFormat": "系统内存占用"
      }
     ]
    }
   ]
  },
  {
   "title": "请求次数统计",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "QPS",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(irate(myapp_gin_http_request_counter{job=\"ginadmin\"}[30s]))by(method,path)",
       "legendFormat": "{{method}}-{{path}}"
      },
      {
       "expr": "sum(irate(myapp_gin_http_request_counter{job=\"ginadmin\"}[30s]))",
       "legendFormat": "qps"
      }
     ]
    },
    {
     "title": "响应时长",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "myapp_gin_http_request_use_time{job=\"ginadmin\"}",
       "legendFormat": "{{method}}-{{path}}"
      }
     ]
    }
   ]
  },
  {
   "title": "请求状态统计",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "请求状态统计",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(irate(myapp_gin_http_request_status{job=\"ginadmin\"}[30s]))by(status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "状态码5xx统计",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
     "targets": [
      {
       "expr": "sum(irate(myapp_gin_http_request_status{job=\"ginadmin\",status=~\"^5.*\"}[30s]))by(method,path)",
       "legendFormat": "{{method}}-{{path}}"
      }
     ]
    },
    {
     "title": "状态码4xx统计",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
     "targets": [
      {
       "expr": "sum(irate(myapp_gin_http_request_status{job=\"ginadmin\",status=~\"^4.*\"}[30s]))by(method,path)",
       "legendFormat": "{{method}}-{{path}}"
      }
     ]
    }
   ]
  }
 ]
}